# Generated by Django 2.1.2 on 2018-10-16 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20181016_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacuna',
            options={'verbose_name': 'Vacuna', 'verbose_name_plural': 'Vacunas'},
        ),
    ]
