# Generated by Django 2.1.3 on 2018-11-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudjugadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
